#!/usr/bin/env node
/**
 * build-nuget.js — assemble the .NET / NuGet delivery from the built dist/.
 *
 * Copies dist/tokens.css into nuget/wwwroot/ (served by the RCL at
 * _content/NewCo.Tokens/newco-tokens.css) and generates a C# constants class
 * mapping PascalCase names to the CSS custom-property names, so Blazor code can
 * reference tokens without magic strings:
 *
 *     style="background: var(@NewCoTokens.SemanticColorLightModeSurfaceSheetBase)"
 *
 * Run AFTER `npm run build-dist`. CI then runs `dotnet pack nuget/`.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const cssPath = resolve(root, "dist", "tokens.css");
const wwwroot = resolve(root, "nuget", "wwwroot");

mkdirSync(wwwroot, { recursive: true });
copyFileSync(cssPath, resolve(wwwroot, "newco-tokens.css"));

const css = readFileSync(cssPath, "utf8");
const names = [...css.matchAll(/(--[a-z0-9-]+)\s*:/g)].map((m) => m[1]);
const pascal = (v) =>
  v.replace(/^--/, "").split("-").filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join("");

const seen = new Set();
const lines = [];
for (const n of names) {
  const id = pascal(n);
  if (seen.has(id)) continue;
  seen.add(id);
  lines.push(`    /// <summary><c>${n}</c></summary>\n    public const string ${id} = "${n}";`);
}

const cs = `// <auto-generated> Generated by scripts/build-nuget.js. Do not edit. </auto-generated>
namespace NewCo.Tokens;

/// <summary>
/// CSS custom-property names for the NewCo (Spired) design tokens.
/// Use with <c>var(...)</c> in Blazor/Razor styles. Values live in
/// <c>_content/NewCo.Tokens/newco-tokens.css</c>.
/// </summary>
public static class NewCoTokens
{
${lines.join("\n")}
}
`;
writeFileSync(resolve(root, "nuget", "NewCoTokens.g.cs"), cs, "utf8");
console.log(`nuget/: copied newco-tokens.css + generated ${seen.size} constants in NewCoTokens.g.cs`);
